### ISSUE TITLE
Will occasionally freeze on a stratagem instead of advancing to the next one, resulting in game over

### ISSUE THREAD

**Issue by Cmonster820** [byjokese/stratagem-hero#1]
see title

**Comment by Cmonster820** [comment]
mostly happens when the level is complete, the 'next up' line appears, but it doesn't change

**Comment by Cmonster820** [comment]
upon further playing it seems it happens when there are 2 of the same stratagem in a row as well

**Comment by byjokese** [comment]
Thanks for the report, did see it happening, but did not manage to get the exact reason of it. With that information I will be able to give it a deeper look, Thanks.

**Comment by byjokese** [comment]
@Cmonster820 Got the solution, thanks for the testing and the detailed case. Got it fixed, as soon as I get a couple of other chores done, will publish the update.

**Comment by Cmonster820** [comment]
thank you

**Comment by byjokese** [comment]
Going to keep the issue open, if that not a problem for you, until I publish it. Thanks!

**Comment by byjokese** [comment]
Fixed on f06e5b98c7f8991b817d2975e9435213ebbab119!
