### ISSUE TITLE
Inconsistent Stratagem Codes in-game & overview

### ISSUE THREAD

**Issue by odil-io** [byjokese/stratagem-hero#9]
When I was "busy" "working" on a solution/PR for #5 I saw the Stratagem code for the LAS-99 go from correct (Down Down Up Left Right) to incorrect (Down Left Down Up Left). It might be a deployment issue. The code is good, online just isn't somehow at the time of typing.

![Screenshot 2024-04-02 at 19-35-08 Stratagem Hero](https://github.com/byjokese/stratagem-hero/assets/2929078/be9fdf97-4472-4906-98a4-3b372a92e466)

And in the Stratagem overview

![Screenshot 2024-04-02 at 19-43-05 Stratagem Hero](https://github.com/byjokese/stratagem-hero/assets/2929078/48da975f-2ba2-4699-9493-9eb27b2ed9ac)

**Comment by byjokese** [comment]
- 'down', 'down', 'up', 'left', 'right' is the `LAS-99 Quasar Cannon`
- 'down', 'left', 'down', 'up', 'left' is the `LAS-98 Laser Cannon`

Both are similar, but different, right? Or I'm missing something 😊

**Comment by odil-io** [comment]
Oh my, you're right! This issue can now be closed :')
